version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: my-spring-boot-app:latest
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db

